CREATE TABLE `sap_customer_order_item_party`
(
            `ObjectID`                                        varchar(70) DEFAULT NULL,
            `ParentObjectID`                                  varchar(70) DEFAULT NULL,
            `Web`                                             varchar(1280) DEFAULT NULL,
            `MobilePhone`                                     varchar(350) DEFAULT NULL,
            `Fax`                                             varchar(350) DEFAULT NULL,
            `Email`                                           varchar(765) DEFAULT NULL,
            `ConventionalPhone`                               varchar(350) DEFAULT NULL,
            `SalesOrderID`                                    varchar(35) DEFAULT NULL,
            `ID`                                              varchar(10) NOT NULL,
            `PreferredCommunicationMediumTypeCode`            varchar(3) DEFAULT NULL,
            `PreferredCommunicationMediumTypeCodeText`        tinyint(1) DEFAULT NULL,
            `PartyID`                                         varchar(60) DEFAULT NULL,
            `RoleCode`                                        varchar(10) DEFAULT NULL,
            `RoleCodeText`                                    tinyint(1) DEFAULT NULL,
            `TimeZoneCode`                                    varchar(10) DEFAULT NULL,
            `TimeZoneCodeText`                                tinyint(1) DEFAULT NULL,
            `StreetSuffixName`                                varchar(240) DEFAULT NULL,
            `StreetPrefixName`                                varchar(240) DEFAULT NULL,
            `StreetName`                                      varchar(360) DEFAULT NULL,
            `FirstLineName`                                   varchar(240) DEFAULT NULL,
            `FourthLineName`                                  varchar(240) DEFAULT NULL,
            `SecondLineName`                                  varchar(240) DEFAULT NULL,
            `ThirdLineName`                                   varchar(240) DEFAULT NULL,
            `CareOfName`                                      varchar(240) DEFAULT NULL,
            `CityName`                                        varchar(240) DEFAULT NULL,
            `CountryCode`                                     varchar(3) DEFAULT NULL,
            `CountryCodeText`                                 tinyint(1) DEFAULT NULL,
            `CountyName`                                      varchar(240) DEFAULT NULL,
            `HouseID`                                         varchar(100) DEFAULT NULL,
            `AdditionalStreetPrefixName`                      varchar(240) DEFAULT NULL,
            `AdditionalStreetSuffixName`                      varchar(240) DEFAULT NULL,
            `POBoxDeviatingCityName`                          varchar(240) DEFAULT NULL,
            `POBoxDeviatingCountryCode`                       varchar(3) DEFAULT NULL,
            `POBoxDeviatingCountryCodeText`                   tinyint(1) DEFAULT NULL,
            `POBoxDeviatingRegionCode`                        varchar(6) DEFAULT NULL,
            `POBoxDeviatingRegionCodeText`                    tinyint(1) DEFAULT NULL,
            `POBoxID`                                         varchar(100) DEFAULT NULL,
            `POBoxIndicator`                                  tinyint(1) DEFAULT NULL,
            `POBoxPostalCode`                                 varchar(100) DEFAULT NULL,
            `RegionCode`                                      varchar(6) DEFAULT NULL,
            `RegionCodeText`                                  tinyint(1) DEFAULT NULL,
            `ETag`                                            tinyint(1) DEFAULT NULL,
    PRIMARY KEY(`ID`)
    CONSTRAINT `SAPCustomerOrderItemParty_fk` FOREIGN KEY (`ID`) REFERENCES `sap_customer_order_item_data` (`ID`)
) ENGINE = InnoDB
 DEFAULT CHARSET = utf8mb4